### ISSUE TITLE
redirect URL incorrect

### ISSUE THREAD

**Issue by adamprocter** [dmorlitz/kanboard-duedate#3]
Installed manually in 1.2.5 as not listed and have found that when changing sorting order the redirect url  is malformed as ://kanban.mydomain.com  should be https:// ? manually editing URL is a work around

**Comment by dmorlitz** [comment]
In that section of code I tried to use $this->app->request->getServerVariable("REQUEST_SCHEME") to detect if you were using HTTP or HTTPS, so I could construct a valid URL each time.  I do my coding and testing on Apache - is it possible that you are using a different web-server which does not define the REQUEST_SCHEME variable?

I have uploaded a new version which does not attempt to set the protocol and hostname.  I realized that this should be sufficient at auto-detecting the proper location.

You will now see a URL redirect that looks like /kanboard/board/14 

Please try this new version and let me know if it fixes your issue......and thank you for pointing out the error.

**Comment by adamprocter** [comment]
excellent works. thank you. I am using CENTOS so should be apache I think... :)
