### ISSUE TITLE
Tasks without due date are on top of those with date

### ISSUE THREAD

**Issue by adamprocter** [dmorlitz/kanboard-duedate#4]
I have a number of tasks that do not have due dates as they can be done 'whenever' but I have a number that have due dates and I would like to be able to show them above the tasks without due date as they are technically more important and need higher visibility. C

**Comment by dmorlitz** [comment]
Interesting idea.....and one I have fiddled with for a while.  I have added a new field to the configuration panel which lets you select what date to assume undated items should have.  This allows you to specify 0 for the top of the list or 12/31/2090 for the bottom (really any date way in the future works)

This also means that you could specify 12/31/2018 - for example.  This would place undated tasks between tasks due this year and future years.  This way undated tasks don't have to be way at the bottom if you have a really long column.

I have only done a little bit of testing - but I think it works.  Please check it out and let me know.

**Comment by dmorlitz** [comment]
You also made me realized that I should move the configuration for a global area to board specific - so you can have different sort orders and default dates per board instead of only at the global level.

I do not think that is hard to do - maybe I will get around to that next week.

**Comment by adamprocter** [comment]
excellent, have to recall the USA date ordering but all good 👍  all my other tasks now due 2090 for now 😊

**Comment by dmorlitz** [comment]
Glad that it works.  I just used the strtotime function so I would think
that it should personalize to your date format.  You can also use a date of
“+90 years” )without the quotes) and you should be good forever.
